@startuml microservice-controller-tasks

!include https://raw.githubusercontent.com/stfsy/plantuml-darkmode/master/dark-component.plantuml

rectangle $whiteText("Services") {
    rectangle Database blue {

    }
}

rectangle $whiteText("Clients") {
    rectangle Client blue {

    }
}

rectangle $whiteText("Microservice") {
    rectangle Provider red {

    }

    rectangle Controller green {

    }

    rectangle Service orange {

    }

    rectangle Cache yellow {

    }
    rectangle RetryTemplate yellow {

    }
}

Client -> Controller

Controller -> Service
' Models <-. Controller

Service -> Provider

' Converter <-. Service
Provider -> Database
Provider --> Cache
Provider --> RetryTemplate

@enduml