@startmindmap mindmaps

title ABCDEF

!include https://raw.githubusercontent.com/stfsy/plantuml-darkmode/master/dark-mindmap.plantuml

+[blue] Transportation
++[green] Planes Red
+++[yellow] Airbus
+++[orange] Boeing
+++[red] Cessna
+++[violet] Cessna
+++[teal] Abc

@endmindmap